baseURL = 'https://www.sanremigioverona.org/'
defaultContentLanguage = 'it'
theme = 'alpha-church'

[languages]
  [languages.it]
    disabled = false
    weight = 0
    languageCode = 'it-IT'
    languageName = 'Italiano'
    title = 'CFRV'

[security]
  enableInlineShortcodes = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Orari"
    url = "/orari"
    weight = 2

  [[menu.main]]
    name = "Chi siamo"
    url = "/presentazione"
    weight = 3

  [[menu.main]]
    name = "Il Coetus"
    parent = "Chi siamo"
    url = "/presentazione"
    weight = 4

  [[menu.main]]
    name = "Il Sacerdote"
    parent = "Chi siamo"
    url = "/celebrante"
    weight = 5
  
  [[menu.main]]
    name = "Contatti"
    url = "/contatti"
    weight = 6

[params]
  title = "Coetus Fidelium San Remigio"
  subtitle = "Liturgia Tridentina a Verona"
  logo = "/img/logo.jpg"
  keywords = [""]
  languageCode = "it"
  instant_page = true
  #bible_popups = "faithlife" #faithlife, blb
  #bible_version = "NRSV-CE"
  customCSS = ["/css/cfrv.css"]

  [params.banner]
    image = "/img/cropped-1.jpg"

  [params.map]
    service = "osm"
    latitude = "45.433527"
    longitude = "11.006372"
    zoom = "18"

  [[params.links]]
    service = "Facebook"
    icon = "fa-facebook"
    icon_pack = "fab"
    link = "//facebook.com/"

  [[params.links]]
    service = "Telegram"
    icon = "fa-telegram"
    icon_pack = "fab"
    link = "//telegram.com/"

[params.contact]
  service = "php"

[params.footer]
  copyright = [
    "Associazione Coetus Fidelium San Remigio",
    "Via Orti Manara, 7 - 37121, Verona (VR)",
    "info@sanremigioverona.org",
    "Privacy & Cookie Policy: su questo sito non raccogliamo dati degli utenti né usiamo cookie."
  ]